# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-07 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=b'3ce1db10bb6a4358aef72cf674504178'),
        ),
    ]
