# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-07 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20200407_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=b'087cadc3e5684633b5148e3b7c4cf512'),
        ),
    ]
