# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-07 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20200407_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=b'925358731ab941c3af9f8639592652a4'),
        ),
    ]
