# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20200407_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=b'2249a2ecc3244edfa94662bfbbbe1245'),
        ),
    ]
