# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-07 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20200407_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='send',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='uuid',
        ),
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
