# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-08 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20200407_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
