# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-09 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=b'05975be655f44c5fa2ac3168f0f3ad98', max_length=64, verbose_name='identifier')),
            ],
            options={
                'verbose_name': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.CharField(blank=True, max_length=170, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meals.Employee')),
            ],
            options={
                'verbose_name': 'Employee Order',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=b'91bd4aa1e71246f7b5cbeee1eb0db772'),
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meals.Menu'),
        ),
        migrations.AddField(
            model_name='order',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meals.Option'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('menu', 'employee')]),
        ),
    ]
