# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20200408_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='employee_identifier',
            field=models.UUIDField(editable=False),
        ),
    ]
