# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-09 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20200409_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.CharField(default=b'130e038496f940318718a3fc3544c5b0', max_length=64, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
