# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-11 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_auto_20200411_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.CharField(default=b'6b7eea05783a47928bae1f03b8c92deb', max_length=64, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
