# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import meals.models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_auto_20200412_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.CharField(default=b'0b60e96dd8304f5fb815cef093a34254', max_length=64, unique=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True
            ),
        ),
    ]

#lunch time