# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_auto_20200412_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.CharField(default=b'2941cb4b9d13454e8affcd4a3d3167ba', max_length=64, unique=True, verbose_name='identifier'),
        ),
    ]
