# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_auto_20200412_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.CharField(default=b'429dd31c1538471b951031f53f0f4403', max_length=64, unique=True, verbose_name='identifier'),
        ),
    ]
