# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-07 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='slack_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.CharField(blank=True, default=b'dde6feae3a3442d3925cc775b853b153', max_length=100, unique=True),
        ),
    ]
