# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-08 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_auto_20200407_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.CharField(blank=True, default=b'78bdb694b71b455bbd0087239a8a6538', max_length=100, unique=True),
        ),
    ]
