# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-08 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_auto_20200407_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default=45666643, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.UUIDField(default=b'bddc71c78c1946eab7fa3654dd34f363', unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, default=5435667, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='slack_id',
            field=models.CharField(blank=True, default=5467568, max_length=10),
            preserve_default=False,
        ),
    ]
