# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-08 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0004_auto_20200407_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.UUIDField(default=b'9cb7463f86bd4a549cab1f503fe14ddc'),
        ),
    ]
