# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-08 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0009_auto_20200407_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slack_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
