# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_delete_order'),
        ('employeeApp', '0010_auto_20200407_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.CharField(blank=True, max_length=170, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_identifier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employeeApp.Employee')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meals.Menu')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meals.Option')),
            ],
            options={
                'verbose_name': 'Employee Order',
            },
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('menu', 'employee_identifier')]),
        ),
    ]
