# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-08 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0011_auto_20200408_0302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='order',
            name='employee_identifier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='option',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
